<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DefaultItemExcludes>$(DefaultItemExcludes);artifacts\**;bin\**;obj\**;src\**\bin\**;src\**\obj\**;tests\**\bin\**;tests\**\obj\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.8" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Program.cs" />
    <Compile Remove="artifacts\**\*.cs" />
    <Compile Remove="obj\**\*.cs" />
    <Compile Remove="src\**\obj\**\*.cs" />
    <Compile Remove="tests\**\*.cs" />
    <Compile Remove="**\*.ide.g.cs" />
    <Content Remove="artifacts\**" />
    <Content Remove="bin\**" />
    <Content Remove="obj\**" />
    <Content Remove="src\**\bin\**" />
    <Content Remove="src\**\obj\**" />
    <Content Remove="tests\**\bin\**" />
    <Content Remove="tests\**\obj\**" />
    <None Remove="artifacts\**" />
    <None Remove="bin\**" />
    <None Remove="obj\**" />
    <None Remove="src\**\bin\**" />
    <None Remove="src\**\obj\**" />
    <None Remove="tests\**\bin\**" />
    <None Remove="tests\**\obj\**" />
    <EmbeddedResource Remove="artifacts\**" />
    <EmbeddedResource Remove="bin\**" />
    <EmbeddedResource Remove="obj\**" />
    <EmbeddedResource Remove="src\**\bin\**" />
    <EmbeddedResource Remove="src\**\obj\**" />
    <EmbeddedResource Remove="tests\**\bin\**" />
    <EmbeddedResource Remove="tests\**\obj\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="src\Neftyanik.Portal.Domain\Entities\Legacy\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="tests\Neftyanik.Portal.Infrastructure.Tests\Neftyanik.Portal.Infrastructure.Tests.csproj" />
  </ItemGroup>

</Project>
