// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Neftyanik.Portal.Infrastructure.Data;

#nullable disable

namespace Neftyanik.Portal.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-administrator",
                            ConcurrencyStamp = "role-administrator",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "role-accountant",
                            ConcurrencyStamp = "role-accountant",
                            Name = "Accountant",
                            NormalizedName = "ACCOUNTANT"
                        },
                        new
                        {
                            Id = "role-member",
                            ConcurrencyStamp = "role-member",
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.AssociationDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UploadedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("AssociationDocuments", (string)null);
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.AssociationElectricityReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AppliedSupplierDayRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("AppliedSupplierNightRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("CurrentDayReading")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("CurrentNightReading")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("DayAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DayConsumption")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<bool>("IsInitialReading")
                        .HasColumnType("bit");

                    b.Property<decimal?>("NightAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NightConsumption")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("PreviousDayReading")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("PreviousNightReading")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateOnly>("ReadingDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("TotalConsumption")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("TotalSupplierAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IsInitialReading")
                        .IsUnique()
                        .HasFilter("[IsInitialReading] = 1");

                    b.HasIndex("ReadingDate")
                        .IsUnique();

                    b.ToTable("AssociationElectricityReadings", null, t =>
                        {
                            t.HasCheckConstraint("CK_AssociationElectricityReadings_CurrentDayReading_NonNegative", "[CurrentDayReading] >= 0");

                            t.HasCheckConstraint("CK_AssociationElectricityReadings_CurrentNightReading_NonNegative", "[CurrentNightReading] >= 0");

                            t.HasCheckConstraint("CK_AssociationElectricityReadings_DayAmount_NonNegative", "[DayAmount] IS NULL OR [DayAmount] >= 0");

                            t.HasCheckConstraint("CK_AssociationElectricityReadings_DayConsumption_NonNegative", "[DayConsumption] IS NULL OR [DayConsumption] >= 0");

                            t.HasCheckConstraint("CK_AssociationElectricityReadings_NightAmount_NonNegative", "[NightAmount] IS NULL OR [NightAmount] >= 0");

                            t.HasCheckConstraint("CK_AssociationElectricityReadings_NightConsumption_NonNegative", "[NightConsumption] IS NULL OR [NightConsumption] >= 0");

                            t.HasCheckConstraint("CK_AssociationElectricityReadings_PreviousDayReading_NonNegative", "[PreviousDayReading] IS NULL OR [PreviousDayReading] >= 0");

                            t.HasCheckConstraint("CK_AssociationElectricityReadings_PreviousNightReading_NonNegative", "[PreviousNightReading] IS NULL OR [PreviousNightReading] >= 0");

                            t.HasCheckConstraint("CK_AssociationElectricityReadings_TotalConsumption_NonNegative", "[TotalConsumption] IS NULL OR [TotalConsumption] >= 0");

                            t.HasCheckConstraint("CK_AssociationElectricityReadings_TotalSupplierAmount_NonNegative", "[TotalSupplierAmount] IS NULL OR [TotalSupplierAmount] >= 0");
                        });
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.AssociationElectricityTariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DayRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<decimal>("NightRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EffectiveFrom")
                        .IsUnique();

                    b.ToTable("AssociationElectricityTariffs", null, t =>
                        {
                            t.HasCheckConstraint("CK_AssociationElectricityTariffs_DayRate_NonNegative", "[DayRate] >= 0");

                            t.HasCheckConstraint("CK_AssociationElectricityTariffs_NightRate_NonNegative", "[NightRate] >= 0");
                        });
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.Charge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("ChargeDate")
                        .HasColumnType("date");

                    b.Property<int>("ChargeTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<int?>("PeriodMonth")
                        .HasColumnType("int");

                    b.Property<int?>("PeriodYear")
                        .HasColumnType("int");

                    b.Property<int?>("PlotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CancelledAtUtc");

                    b.HasIndex("ChargeDate");

                    b.HasIndex("ChargeTypeId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DueDate");

                    b.HasIndex("PlotId");

                    b.ToTable("Charges", null, t =>
                        {
                            t.HasCheckConstraint("CK_Charges_Amount_Positive", "[Amount] >= 0");

                            t.HasCheckConstraint("CK_Charges_DueDate_NotEarlierThanChargeDate", "[DueDate] IS NULL OR [DueDate] >= [ChargeDate]");

                            t.HasCheckConstraint("CK_Charges_PeriodMonth_Range", "[PeriodMonth] IS NULL OR ([PeriodMonth] >= 1 AND [PeriodMonth] <= 12)");

                            t.HasCheckConstraint("CK_Charges_PeriodYear_Range", "[PeriodYear] IS NULL OR ([PeriodYear] >= 2000 AND [PeriodYear] <= 2100)");
                        });
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.ChargeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DefaultAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsYearly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("OnlyOnOwnerChange")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasFilter("[IsDefault] = 1 AND [IsActive] = 1");

                    b.HasIndex("Name");

                    b.ToTable("ChargeTypes", null, t =>
                        {
                            t.HasCheckConstraint("CK_ChargeTypes_DefaultAmount_Positive", "[DefaultAmount] IS NULL OR [DefaultAmount] > 0");

                            t.HasCheckConstraint("CK_ChargeTypes_YearlyAndOwnerChangeExclusive", "[IsYearly] = 0 OR [OnlyOnOwnerChange] = 0");
                        });
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.ElectricityMeter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("InitialDayReading")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("InitialNightReading")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("InitialReading")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateOnly?>("InstallationDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MeterKind")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TariffMode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("ElectricityMeters", (string)null);
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.ElectricityReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChargeId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("CurrentDayReading")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("CurrentNightReading")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("DayAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DayConsumption")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("DayRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsInitialReading")
                        .HasColumnType("bit");

                    b.Property<decimal?>("NightAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NightConsumption")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("NightRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("PlotId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PreviousDayReading")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("PreviousNightReading")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateOnly>("ReadingDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ChargeId")
                        .IsUnique()
                        .HasFilter("[ChargeId] IS NOT NULL");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PlotId");

                    b.HasIndex("PlotId", "ReadingDate")
                        .IsUnique();

                    b.ToTable("ElectricityReadings", null, t =>
                        {
                            t.HasCheckConstraint("CK_ElectricityReadings_CurrentDayReading_NonNegative", "[CurrentDayReading] >= 0");

                            t.HasCheckConstraint("CK_ElectricityReadings_CurrentNightReading_NonNegative", "[CurrentNightReading] >= 0");

                            t.HasCheckConstraint("CK_ElectricityReadings_DayAmount_NonNegative", "[DayAmount] IS NULL OR [DayAmount] >= 0");

                            t.HasCheckConstraint("CK_ElectricityReadings_DayConsumption_NonNegative", "[DayConsumption] IS NULL OR [DayConsumption] >= 0");

                            t.HasCheckConstraint("CK_ElectricityReadings_NightAmount_NonNegative", "[NightAmount] IS NULL OR [NightAmount] >= 0");

                            t.HasCheckConstraint("CK_ElectricityReadings_NightConsumption_NonNegative", "[NightConsumption] IS NULL OR [NightConsumption] >= 0");

                            t.HasCheckConstraint("CK_ElectricityReadings_PreviousDayReading_NonNegative", "[PreviousDayReading] IS NULL OR [PreviousDayReading] >= 0");

                            t.HasCheckConstraint("CK_ElectricityReadings_PreviousNightReading_NonNegative", "[PreviousNightReading] IS NULL OR [PreviousNightReading] >= 0");

                            t.HasCheckConstraint("CK_ElectricityReadings_TotalAmount_NonNegative", "[TotalAmount] IS NULL OR [TotalAmount] >= 0");
                        });
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.ElectricityTariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DayRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<decimal>("NightRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EffectiveFrom")
                        .IsUnique();

                    b.ToTable("ElectricityTariffs", null, t =>
                        {
                            t.HasCheckConstraint("CK_ElectricityTariffs_DayRate_NonNegative", "[DayRate] >= 0");

                            t.HasCheckConstraint("CK_ElectricityTariffs_NightRate_NonNegative", "[NightRate] >= 0");
                        });
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.Expense", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("AssociationElectricityReadingId")
                        .HasColumnType("bigint");

                    b.Property<string>("AttachmentPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ExpenseCategoryId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ExpenseDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<string>("Payee")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AssociationElectricityReadingId")
                        .IsUnique()
                        .HasFilter("[AssociationElectricityReadingId] IS NOT NULL");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ExpenseCategoryId");

                    b.HasIndex("ExpenseDate");

                    b.ToTable("Expenses", (string)null);
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.ExpenseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ExpenseCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Электроэнергия"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Охрана"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Зарплата бухгалтеру и председателю"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Покупка нового имущества для кооператива"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Ремонт имущества для кооператива"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Наемный труд для кооператива"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = false,
                            Name = "Административные расходы"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = false,
                            Name = "Налоги и банковские комиссии"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = false,
                            Name = "Прочее"
                        });
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasMaxLength(450)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateOnly?>("JoinedAt")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("Email");

                    b.HasIndex("FullName");

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.MemberElectricityMeter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillingPlotId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("MeterNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("BillingPlotId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("MemberId");

                    b.ToTable("MemberElectricityMeters", (string)null);
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.MemberElectricityMeterPlot", b =>
                {
                    b.Property<int>("MemberElectricityMeterId")
                        .HasColumnType("int");

                    b.Property<int>("PlotId")
                        .HasColumnType("int");

                    b.HasKey("MemberElectricityMeterId", "PlotId");

                    b.HasIndex("PlotId");

                    b.ToTable("MemberElectricityMeterPlots", (string)null);
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.MemberElectricityReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AppliedMemberRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<long?>("ChargeId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Consumption")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("CurrentReading")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<bool>("IsInitialReading")
                        .HasColumnType("bit");

                    b.Property<int>("MemberElectricityMeterId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PreviousReading")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateOnly>("ReadingDate")
                        .HasColumnType("date");

                    b.Property<bool>("SubmittedByMember")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ChargeId")
                        .IsUnique()
                        .HasFilter("[ChargeId] IS NOT NULL");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("MemberElectricityMeterId", "IsInitialReading")
                        .IsUnique()
                        .HasFilter("[IsInitialReading] = 1");

                    b.HasIndex("MemberElectricityMeterId", "ReadingDate")
                        .IsUnique();

                    b.ToTable("MemberElectricityReadings", null, t =>
                        {
                            t.HasCheckConstraint("CK_MemberElectricityReadings_Amount_NonNegative", "[Amount] IS NULL OR [Amount] >= 0");

                            t.HasCheckConstraint("CK_MemberElectricityReadings_AppliedMemberRate_NonNegative", "[AppliedMemberRate] IS NULL OR [AppliedMemberRate] >= 0");

                            t.HasCheckConstraint("CK_MemberElectricityReadings_Consumption_NonNegative", "[Consumption] IS NULL OR [Consumption] >= 0");

                            t.HasCheckConstraint("CK_MemberElectricityReadings_CurrentReading_NonNegative", "[CurrentReading] >= 0");

                            t.HasCheckConstraint("CK_MemberElectricityReadings_PreviousReading_NonNegative", "[PreviousReading] IS NULL OR [PreviousReading] >= 0");
                        });
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.MemberElectricityTariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EffectiveFrom")
                        .IsUnique();

                    b.ToTable("MemberElectricityTariffs", null, t =>
                        {
                            t.HasCheckConstraint("CK_MemberElectricityTariffs_Rate_NonNegative", "[Rate] >= 0");
                        });
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.MembershipFeeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPerPlot")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("MembershipFeeRates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountPerPlot = 500.00m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DueDate = new DateOnly(2026, 12, 31),
                            IsActive = true,
                            Year = 2026
                        });
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.MeterPlot", b =>
                {
                    b.Property<int>("MeterId")
                        .HasColumnType("int");

                    b.Property<int>("PlotId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("MeterId", "PlotId", "ValidFrom");

                    b.HasIndex("PlotId");

                    b.ToTable("MeterPlots", (string)null);
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.MeterReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ApprovedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("DayValue")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("MeterId")
                        .HasColumnType("int");

                    b.Property<string>("MeterPhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("NightValue")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateOnly>("ReadingDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SubmittedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("TotalValue")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("SubmittedByUserId");

                    b.HasIndex("MeterId", "ReadingDate")
                        .IsUnique();

                    b.ToTable("MeterReadings", (string)null);
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.NewsArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IsPublished", "PublishedAt");

                    b.ToTable("NewsArticles", (string)null);
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int?>("PlotId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CancelledAtUtc");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PaymentDate");

                    b.HasIndex("PlotId");

                    b.HasIndex("ReferenceNumber");

                    b.ToTable("Payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Payments_Amount_Positive", "[Amount] > 0");
                        });
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.PaymentAllocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ChargeId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("PaymentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChargeId");

                    b.HasIndex("PaymentId");

                    b.ToTable("PaymentAllocations", (string)null);
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.Plot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal?>("AreaSquareMeters")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CadastralNumber")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CadastralNumber");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Plots", (string)null);
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.PlotOwnership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPrimaryContact")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<decimal?>("OwnershipShare")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("PlotId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("PlotId")
                        .IsUnique()
                        .HasFilter("[ValidTo] IS NULL");

                    b.ToTable("PlotOwnerships", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlotOwnerships_OwnershipShare_Range", "[OwnershipShare] IS NULL OR ([OwnershipShare] > 0 AND [OwnershipShare] <= 100)");

                            t.HasCheckConstraint("CK_PlotOwnerships_ValidTo_NotEarlierThanValidFrom", "[ValidFrom] IS NULL OR [ValidTo] IS NULL OR [ValidTo] >= [ValidFrom]");
                        });
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.PlotOwnershipHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PlotId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PlotId");

                    b.ToTable("PlotOwnershipHistories", (string)null);
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("SystemSettings", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Neftyanik.Portal.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Neftyanik.Portal.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Neftyanik.Portal.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Neftyanik.Portal.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.AssociationDocument", b =>
                {
                    b.HasOne("Neftyanik.Portal.Domain.Entities.ApplicationUser", "UploadedByUser")
                        .WithMany("UploadedDocuments")
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.AssociationElectricityReading", b =>
                {
                    b.HasOne("Neftyanik.Portal.Domain.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany("CreatedAssociationElectricityReadings")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.AssociationElectricityTariff", b =>
                {
                    b.HasOne("Neftyanik.Portal.Domain.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany("CreatedAssociationElectricityTariffs")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Neftyanik.Portal.Domain.Entities.ApplicationUser", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.Charge", b =>
                {
                    b.HasOne("Neftyanik.Portal.Domain.Entities.ChargeType", "ChargeType")
                        .WithMany("Charges")
                        .HasForeignKey("ChargeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Neftyanik.Portal.Domain.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany("CreatedCharges")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Neftyanik.Portal.Domain.Entities.Plot", "Plot")
                        .WithMany("Charges")
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChargeType");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Plot");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.ElectricityMeter", b =>
                {
                    b.HasOne("Neftyanik.Portal.Domain.Entities.ApplicationUser", "Owner")
                        .WithMany("ElectricityMeters")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.ElectricityReading", b =>
                {
                    b.HasOne("Neftyanik.Portal.Domain.Entities.Charge", "Charge")
                        .WithOne("ElectricityReading")
                        .HasForeignKey("Neftyanik.Portal.Domain.Entities.ElectricityReading", "ChargeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Neftyanik.Portal.Domain.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany("CreatedElectricityReadings")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Neftyanik.Portal.Domain.Entities.Plot", "Plot")
                        .WithMany("ElectricityReadings")
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Charge");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Plot");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.ElectricityTariff", b =>
                {
                    b.HasOne("Neftyanik.Portal.Domain.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany("CreatedElectricityTariffs")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.Expense", b =>
                {
                    b.HasOne("Neftyanik.Portal.Domain.Entities.AssociationElectricityReading", "AssociationElectricityReading")
                        .WithOne("SupplierExpense")
                        .HasForeignKey("Neftyanik.Portal.Domain.Entities.Expense", "AssociationElectricityReadingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Neftyanik.Portal.Domain.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany("CreatedExpenses")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Neftyanik.Portal.Domain.Entities.ExpenseCategory", "ExpenseCategory")
                        .WithMany("Expenses")
                        .HasForeignKey("ExpenseCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssociationElectricityReading");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ExpenseCategory");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.Member", b =>
                {
                    b.HasOne("Neftyanik.Portal.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("Members")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.MemberElectricityMeter", b =>
                {
                    b.HasOne("Neftyanik.Portal.Domain.Entities.Plot", "BillingPlot")
                        .WithMany("BillingMemberElectricityMeters")
                        .HasForeignKey("BillingPlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Neftyanik.Portal.Domain.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany("CreatedMemberElectricityMeters")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Neftyanik.Portal.Domain.Entities.Member", "Member")
                        .WithMany("MemberElectricityMeters")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BillingPlot");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.MemberElectricityMeterPlot", b =>
                {
                    b.HasOne("Neftyanik.Portal.Domain.Entities.MemberElectricityMeter", "MemberElectricityMeter")
                        .WithMany("MeterPlots")
                        .HasForeignKey("MemberElectricityMeterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Neftyanik.Portal.Domain.Entities.Plot", "Plot")
                        .WithMany("MemberElectricityMeterPlots")
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MemberElectricityMeter");

                    b.Navigation("Plot");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.MemberElectricityReading", b =>
                {
                    b.HasOne("Neftyanik.Portal.Domain.Entities.Charge", "Charge")
                        .WithOne("MemberElectricityReading")
                        .HasForeignKey("Neftyanik.Portal.Domain.Entities.MemberElectricityReading", "ChargeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Neftyanik.Portal.Domain.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany("CreatedMemberElectricityReadings")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Neftyanik.Portal.Domain.Entities.MemberElectricityMeter", "MemberElectricityMeter")
                        .WithMany("Readings")
                        .HasForeignKey("MemberElectricityMeterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Charge");

                    b.Navigation("CreatedByUser");

                    b.Navigation("MemberElectricityMeter");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.MemberElectricityTariff", b =>
                {
                    b.HasOne("Neftyanik.Portal.Domain.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany("CreatedMemberElectricityTariffs")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.MeterPlot", b =>
                {
                    b.HasOne("Neftyanik.Portal.Domain.Entities.ElectricityMeter", "Meter")
                        .WithMany("MeterPlots")
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Neftyanik.Portal.Domain.Entities.Plot", "Plot")
                        .WithMany("MeterPlots")
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meter");

                    b.Navigation("Plot");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.MeterReading", b =>
                {
                    b.HasOne("Neftyanik.Portal.Domain.Entities.ApplicationUser", "ApprovedByUser")
                        .WithMany("ApprovedMeterReadings")
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Neftyanik.Portal.Domain.Entities.ElectricityMeter", "Meter")
                        .WithMany("MeterReadings")
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Neftyanik.Portal.Domain.Entities.ApplicationUser", "SubmittedByUser")
                        .WithMany("SubmittedMeterReadings")
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Meter");

                    b.Navigation("SubmittedByUser");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.NewsArticle", b =>
                {
                    b.HasOne("Neftyanik.Portal.Domain.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany("CreatedNewsArticles")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Neftyanik.Portal.Domain.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany("CreatedPayments")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Neftyanik.Portal.Domain.Entities.Plot", "Plot")
                        .WithMany("Payments")
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Plot");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.PaymentAllocation", b =>
                {
                    b.HasOne("Neftyanik.Portal.Domain.Entities.Charge", "Charge")
                        .WithMany("PaymentAllocations")
                        .HasForeignKey("ChargeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Neftyanik.Portal.Domain.Entities.Payment", "Payment")
                        .WithMany("PaymentAllocations")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Charge");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.PlotOwnership", b =>
                {
                    b.HasOne("Neftyanik.Portal.Domain.Entities.Member", "Member")
                        .WithMany("PlotOwnerships")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Neftyanik.Portal.Domain.Entities.Plot", "Plot")
                        .WithMany("PlotOwnerships")
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Plot");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.PlotOwnershipHistory", b =>
                {
                    b.HasOne("Neftyanik.Portal.Domain.Entities.ApplicationUser", "Owner")
                        .WithMany("PlotOwnershipHistoryRecords")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Neftyanik.Portal.Domain.Entities.Plot", "Plot")
                        .WithMany("OwnershipHistory")
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Plot");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.SystemSetting", b =>
                {
                    b.HasOne("Neftyanik.Portal.Domain.Entities.ApplicationUser", "UpdatedByUser")
                        .WithMany("UpdatedSystemSettings")
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("ApprovedMeterReadings");

                    b.Navigation("AuditLogs");

                    b.Navigation("CreatedAssociationElectricityReadings");

                    b.Navigation("CreatedAssociationElectricityTariffs");

                    b.Navigation("CreatedCharges");

                    b.Navigation("CreatedElectricityReadings");

                    b.Navigation("CreatedElectricityTariffs");

                    b.Navigation("CreatedExpenses");

                    b.Navigation("CreatedMemberElectricityMeters");

                    b.Navigation("CreatedMemberElectricityReadings");

                    b.Navigation("CreatedMemberElectricityTariffs");

                    b.Navigation("CreatedNewsArticles");

                    b.Navigation("CreatedPayments");

                    b.Navigation("ElectricityMeters");

                    b.Navigation("Members");

                    b.Navigation("PlotOwnershipHistoryRecords");

                    b.Navigation("SubmittedMeterReadings");

                    b.Navigation("UpdatedSystemSettings");

                    b.Navigation("UploadedDocuments");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.AssociationElectricityReading", b =>
                {
                    b.Navigation("SupplierExpense");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.Charge", b =>
                {
                    b.Navigation("ElectricityReading");

                    b.Navigation("MemberElectricityReading");

                    b.Navigation("PaymentAllocations");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.ChargeType", b =>
                {
                    b.Navigation("Charges");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.ElectricityMeter", b =>
                {
                    b.Navigation("MeterPlots");

                    b.Navigation("MeterReadings");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.ExpenseCategory", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.Member", b =>
                {
                    b.Navigation("MemberElectricityMeters");

                    b.Navigation("PlotOwnerships");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.MemberElectricityMeter", b =>
                {
                    b.Navigation("MeterPlots");

                    b.Navigation("Readings");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.Payment", b =>
                {
                    b.Navigation("PaymentAllocations");
                });

            modelBuilder.Entity("Neftyanik.Portal.Domain.Entities.Plot", b =>
                {
                    b.Navigation("BillingMemberElectricityMeters");

                    b.Navigation("Charges");

                    b.Navigation("ElectricityReadings");

                    b.Navigation("MemberElectricityMeterPlots");

                    b.Navigation("MeterPlots");

                    b.Navigation("OwnershipHistory");

                    b.Navigation("Payments");

                    b.Navigation("PlotOwnerships");
                });
#pragma warning restore 612, 618
        }
    }
}
